# Generated by Django 5.2.8 on 2025-12-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Dairy', 'Dairy'), ('Groceries', 'Groceries'), ('Health', 'Health'), ('Shopping', 'Shopping'), ('Electronics', 'Electronics'), ('Education', 'Education'), ('Travel', 'Travel'), ('Rent', 'Rent'), ('Bill', 'Bill'), ('Entertainment', 'Entertainment'), ('Gifts', 'Gifts'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=50),
        ),
    ]
